### PR TITLE
Don't prompt for libc type when not on Linux

### LINKED ISSUE #178: Installation on macOS 10.15 fails with "Unable to determine libc type"
I'm trying to install Pony on macOS 10.15 and it's a bit of a struggle.

When I run `ponyup-init.sh` I get a message "Unable to determine libc type. Pease select one of the following" which shows me options for glibc and musl (though no option for macOS's libc.) If I choose musl or glibc, the init script succeeds, but the resulting ponyup program fails on startup with the message "error: unable to determine platform (/Users/rsms/.local/share/ponyup/.platform)" (note: this is not the prefix I installed ponyup at, as you can see in the full transcript below.)

Summary:

1. init script seems to think that I'm running Linux (since it asks me to choose one of two linux-specific libcs)
2. ponyup seems to have installation location hard coded (which is apparently not updated by the init script)

## What I did

1. Read ["what you need"](https://tutorial.ponylang.io/getting-started/what-you-need.html#the-pony-compiler) and follow the link to...
2. where I follow another link ["Prebuilt macOS for Intel packages are available via ponyup"](https://github.com/ponylang/ponyc/blob/main/INSTALL.md#macos) which takes me to...
3. <https://github.com/ponylang/ponyup> where I scroll to the [readme section about installing](https://github.com/ponylang/ponyup#install-dependencies)

### Transcript

(note that `;` is my prompt)

```
; brew install libressl
...
==> Downloading https://homebrew.bintray.com/bottles/libressl-3.2.5.catalina.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/e7939bc3161bc0120701c3afaaa7035a32ba521c4e9859132f9
######################################################################## 100.0%
==> Pouring libressl-3.2.5.catalina.bottle.tar.g
...
; XDG_DATA_HOME=$HOME/.pony sh -c "$(curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/ponylang/ponyup/latest-release/ponyup-init.sh)"
ponyup_root = /Users/rsms/.pony/ponyup
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3494  100  3494    0     0   5662      0 --:--:-- --:--:-- --:--:--  5662
checksum=351a0b5b553bcb249f6bcd08461b05fe57c8a3280e508b0ac141e266d259ca28
dl_url=https://dl.cloudsmith.io/public/ponylang/nightlies/raw/versions/20210318/ponyup-x86-64-apple-darwin.tar.gz
downloading ponyup-x86-64-apple-darwin.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  244k  100  244k    0     0   751k      0 --:--:-- --:--:-- --:--:--  749k
checksum ok
ponyup placed in /Users/rsms/.pony/ponyup/bin
You should add /Users/rsms/.pony/ponyup/bin to $PATH:
export PATH=/Users/rsms/.pony/ponyup/bin:$PATH
Unable to determine libc type. Pease select one of the following:
1) glibc
2) musl
3) cancel
selection: 2
setting default platform to x86_64-apple-darwin-musl
; /Users/rsms/.pony/ponyup/bin/ponyup update ponyc release
error: unable to determine platform (/Users/rsms/.local/share/ponyup/.platform)
;
```

Environment

```
; uname -srm
Darwin 19.6.0 x86_64
; echo $SHELL
/bin/zsh
; clang --version
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
; cat /Users/rsms/.local/share/ponyup/.platform
cat: /Users/rsms/.local/share/ponyup/.platform: No such file or directory
```

### PR DESCRIPTION
**Pull request by SeanTAllen**
Currently, Darwin users are prompted for the libc type. This shouldn't
be happening. Only Linux users should get prompted.

Closes #178

### CODE REVIEW

**Comment by ponylang-main** [comment]
Hi @SeanTAllen,

The changelog - fixed label was added to this pull request; all PRs with a changelog label need to have release notes included as part of the PR. If you haven't added release notes already, please do.

Release notes are added by creating a uniquely named file in the `.release-notes` directory. We suggest you call the file `179.md` to match the number of this pull request.

The basic format of the release notes (using markdown) should be:

```
## Title

End user description of changes, why it's important,
problems it solves etc.

If a breaking change, make sure to include 1 or more
examples what code would look like prior to this change
and how to update it to work after this change.
```

Thanks.

File: ponyup-init.sh [hunk 1]
```diff
@@ -96,7 +96,31 @@ Linux*)
   *musl)
     platform_triple_distro="musl"
     ;;
-  *) ;;
+  *)
+    while true; do
+      echo "Unable to determine libc type. P;ease select one of the following:"
```
Comment (Theodus) [inline ponyup-init.sh:101]:
```suggestion
      echo "Unable to determine libc type. Please select one of the following:"
```

**Review by Theodus — APPROVED** [review]
Looks good. Thanks! Just one suggested fix for an existing typo.

**Review by Theodus — APPROVED** [review]
LGTM
